<#
.SYNOPSIS
    Creates Entra ID (Azure AD) users matching the 10 synthetic customer profiles
    generated by the Generate_Credit_Card_Transactions notebook.

.DESCRIPTION
    This script provisions Entra ID users with UPNs matching the customer table so that
    transactions can be correlated with real identity objects.

    Prerequisites:
      - Azure CLI installed and logged in (az login)
      - Sufficient privileges to create users (User Administrator or Global Administrator)

.PARAMETER CsvPath
    Path to a CSV file containing customer data. The CSV must have these columns:
    first_name, last_name, email (and optionally home_city, home_state, country_code).
    Defaults to the latest "customers_*.csv" in the script directory, or "customers.csv".

.PARAMETER CsvPath
    Path to a CSV file containing customer data. The CSV must have these columns:
    first_name, last_name, email (and optionally home_city, home_state, country_code).
    Defaults to the latest "customers_*.csv" in the script directory, or "customers.csv".

.EXAMPLE
    .\Create-EntraID-Customers.ps1

.EXAMPLE
    .\Create-EntraID-Customers.ps1 -CsvPath "C:\data\customers.csv"
#>

param(
    [Parameter(Mandatory = $false)]
    [string]$CsvPath
)

# ── Prompt for credentials ────────────────────────────────────────────
$TenantName = Read-Host "Enter your Entra ID tenant name (e.g. contoso or contoso.onmicrosoft.com)"
$DefaultPassword = Read-Host "Enter the default password for all users" -AsSecureString

# Normalize tenant domain
if ($TenantName -notlike "*.onmicrosoft.com") {
    $TenantDomain = "$TenantName.onmicrosoft.com"
}
else {
    $TenantDomain = $TenantName
}

# Auto-detect latest customers_*.csv if no path specified
if (-not $CsvPath) {
    $csvFiles = Get-ChildItem -Path $PSScriptRoot -Filter "customers_*.csv" | Sort-Object Name
    if ($csvFiles) {
        $CsvPath = $csvFiles[-1].FullName
    }
    else {
        $CsvPath = Join-Path $PSScriptRoot "customers.csv"
    }
}

# Convert SecureString to plain text for az CLI (which requires plain text)
$PlainPassword = [Runtime.InteropServices.Marshal]::PtrToStringAuto(
    [Runtime.InteropServices.Marshal]::SecureStringToBSTR($DefaultPassword)
)

# ── Load customers from CSV ───────────────────────────────────────────
if (-not (Test-Path $CsvPath)) {
    Write-Error "CSV file not found: $CsvPath"
    exit 1
}
$customers = Import-Csv -Path $CsvPath

Write-Host "============================================" -ForegroundColor Cyan
Write-Host " Entra ID Customer User Provisioning Script" -ForegroundColor Cyan
Write-Host "============================================" -ForegroundColor Cyan
Write-Host ""
Write-Host "CSV file: $CsvPath"
Write-Host "Tenant domain: $TenantDomain"
Write-Host "Users to create: $($customers.Count)"
Write-Host ""

# ── Check for Azure CLI ───────────────────────────────────
$azAvailable = Get-Command az -ErrorAction SilentlyContinue
if (-not $azAvailable) {
    Write-Error "Azure CLI (az) is not installed or not in PATH. Install from https://aka.ms/installazurecli"
    exit 1
}

# Verify login
az account show --output none 2>$null
if ($LASTEXITCODE -ne 0) {
    Write-Host "Not logged in. Running 'az login'..." -ForegroundColor Yellow
    az login --output none
    if ($LASTEXITCODE -ne 0) {
        Write-Error "Azure login failed. Please run 'az login' manually."
        exit 1
    }
}

# ── Create users ──────────────────────────────────────────
$created = 0
$skipped = 0
$failed = 0

foreach ($customer in $customers) {
    # Replace domain in CSV email with the specified tenant domain
    $upn = ($customer.email -split '@')[0] + '@' + $TenantDomain
    $displayName = "$($customer.first_name) $($customer.last_name)"

    Write-Host "Processing: $displayName ($upn)..." -NoNewline

    # Check if user already exists
    az ad user show --id $upn --output none 2>$null
    if ($LASTEXITCODE -eq 0) {
        Write-Host " SKIPPED (already exists)" -ForegroundColor Yellow
        $skipped++
        continue
    }

    # Create the user
    $mailNickname = $upn.Split('@')[0]

    # Wrap values that may contain cmd.exe metacharacters (e.g. '&' in the
    # password) in double quotes. az is a batch file (az.cmd) on Windows and
    # PowerShell 5.1 only auto-quotes native-command arguments containing
    # spaces, so an unquoted '&' would split the command line inside az.cmd.
    $azArgs = @(
        'ad', 'user', 'create',
        '--display-name', $displayName,
        '--user-principal-name', $upn,
        '--password', "`"$PlainPassword`"",
        '--force-change-password-next-sign-in', 'true',
        '--mail-nickname', $mailNickname,
        '--output', 'none'
    )
    $errorOutput = & az @azArgs 2>&1

    if ($LASTEXITCODE -eq 0) {
        Write-Host " CREATED" -ForegroundColor Green
        $created++
    }
    else {
        Write-Host " FAILED" -ForegroundColor Red
        Write-Host "    Error: $errorOutput" -ForegroundColor DarkRed
        $failed++
    }
}

# ── Summary ───────────────────────────────────────────────
Write-Host ""
Write-Host "============================================" -ForegroundColor Cyan
Write-Host " Summary" -ForegroundColor Cyan
Write-Host "============================================" -ForegroundColor Cyan
Write-Host "  Created: $created" -ForegroundColor Green
Write-Host "  Skipped: $skipped" -ForegroundColor Yellow
Write-Host "  Failed:  $failed" -ForegroundColor Red
Write-Host ""
Write-Host "Users are set with force-change-password-next-sign-in."
Write-Host "UPNs match the notebook's customers table for identity correlation."
