@baseUrl = http://localhost:7071

GET {{baseUrl}}/api/session/new
Content-Type: application/json
###

GET {{baseUrl}}/api/stream
Content-Type: application/json

###

# After calling session/new, copy the full JSON response into the "session" field below
POST {{baseUrl}}/api/conversation
Content-Type: application/json

{
  "prompt": "Hi my name is Hugo",  
  "sessionInfo": {
    "sessionId": "5e7947d6-1130-419e-b119-32732b42f7c6",
    "serviceSessionId": ""    
  }
}
