<#
.SYNOPSIS
    Creates Entra ID (Azure AD) users matching the 10 synthetic customer profiles
    generated by the Generate_Credit_Card_Transactions notebook.

.DESCRIPTION
    This script provisions Entra ID users with UPNs matching the customer table so that
    transactions can be correlated with real identity objects.

    Prerequisites:
      - Azure CLI installed and logged in (az login)
      - Sufficient privileges to create users (User Administrator or Global Administrator)

.PARAMETER TenantDomain
    The Entra ID tenant domain (e.g., "contoso.onmicrosoft.com").

.PARAMETER DefaultPassword
    The initial password for all created users. Users will be prompted to change it on first sign-in.

.EXAMPLE
    .\Create-EntraID-Customers.ps1 -TenantDomain "contoso.onmicrosoft.com" -DefaultPassword (ConvertTo-SecureString "P@ssw0rd!234" -AsPlainText -Force)

.EXAMPLE
    # Interactive (prompted with masked input)
    .\Create-EntraID-Customers.ps1 -TenantDomain "contoso.onmicrosoft.com"
#>

param(
    [Parameter(Mandatory = $true)]
    [string]$TenantDomain,

    [Parameter(Mandatory = $true)]
    [SecureString]$DefaultPassword
)

# Convert SecureString to plain text for az CLI (which requires plain text)
$PlainPassword = [Runtime.InteropServices.Marshal]::PtrToStringAuto(
    [Runtime.InteropServices.Marshal]::SecureStringToBSTR($DefaultPassword)
)

# ── Customer definitions (must match notebook seed=42, NUM_USERS=10) ──────
# These are generated deterministically by Faker with seed 42 to match the notebook.
# If you change the notebook seed or user count, re-export the user list and update here.
$customers = @(
    @{ FirstName = "Allison";  LastName = "Hill";      City = "São Paulo";     State = "SP"; Country = "BR" }
    @{ FirstName = "Norma";    LastName = "Fisher";    City = "Halifax";       State = "NS"; Country = "CA" }
    @{ FirstName = "Nicholas"; LastName = "Macias";    City = "Edmonton";      State = "AB"; Country = "CA" }
    @{ FirstName = "Jason";    LastName = "Flores";    City = "Curitiba";      State = "PR"; Country = "BR" }
    @{ FirstName = "Michelle"; LastName = "Gonzalez";  City = "Calgary";       State = "AB"; Country = "CA" }
    @{ FirstName = "Tiffany";  LastName = "Mcdonald";  City = "San Diego";     State = "CA"; Country = "US" }
    @{ FirstName = "Norman";   LastName = "Moon";      City = "Nashville";     State = "TN"; Country = "US" }
    @{ FirstName = "Sandra";   LastName = "Ray";       City = "Alajuela";      State = "AL"; Country = "CR" }
    @{ FirstName = "Brian";    LastName = "Kelly";     City = "Heredia";       State = "HE"; Country = "CR" }
    @{ FirstName = "Michelle"; LastName = "Lane";      City = "Las Vegas";     State = "NV"; Country = "US" }
)

Write-Host "============================================" -ForegroundColor Cyan
Write-Host " Entra ID Customer User Provisioning Script" -ForegroundColor Cyan
Write-Host "============================================" -ForegroundColor Cyan
Write-Host ""
Write-Host "Tenant domain: $TenantDomain"
Write-Host "Users to create: $($customers.Count)"
Write-Host ""

# ── Check for Azure CLI ───────────────────────────────────
$azAvailable = Get-Command az -ErrorAction SilentlyContinue
if (-not $azAvailable) {
    Write-Error "Azure CLI (az) is not installed or not in PATH. Install from https://aka.ms/installazurecli"
    exit 1
}

# Verify login
az account show --output none 2>$null
if ($LASTEXITCODE -ne 0) {
    Write-Host "Not logged in. Running 'az login'..." -ForegroundColor Yellow
    az login --output none
    if ($LASTEXITCODE -ne 0) {
        Write-Error "Azure login failed. Please run 'az login' manually."
        exit 1
    }
}

# ── Create users ──────────────────────────────────────────
$created = 0
$skipped = 0
$failed = 0

foreach ($customer in $customers) {
    $upn = "$($customer.FirstName.ToLower()).$($customer.LastName.ToLower())@$TenantDomain"
    $displayName = "$($customer.FirstName) $($customer.LastName)"

    Write-Host "Processing: $displayName ($upn)..." -NoNewline

    # Check if user already exists
    az ad user show --id $upn --output none 2>$null
    if ($LASTEXITCODE -eq 0) {
        Write-Host " SKIPPED (already exists)" -ForegroundColor Yellow
        $skipped++
        continue
    }

    # Create the user
    $mailNickname = "$($customer.FirstName.ToLower()).$($customer.LastName.ToLower())"
    $givenName = $customer.FirstName
    $surname = $customer.LastName

    az ad user create `
        --display-name $displayName `
        --user-principal-name $upn `
        --password $PlainPassword `
        --force-change-password-next-sign-in true `
        --mail-nickname $mailNickname `
        --given-name $givenName `
        --surname $surname `
        --output none 2>$null

    if ($LASTEXITCODE -eq 0) {
        Write-Host " CREATED" -ForegroundColor Green
        $created++
    } else {
        Write-Host " FAILED" -ForegroundColor Red
        $failed++
    }
}

# ── Summary ───────────────────────────────────────────────
Write-Host ""
Write-Host "============================================" -ForegroundColor Cyan
Write-Host " Summary" -ForegroundColor Cyan
Write-Host "============================================" -ForegroundColor Cyan
Write-Host "  Created: $created" -ForegroundColor Green
Write-Host "  Skipped: $skipped" -ForegroundColor Yellow
Write-Host "  Failed:  $failed" -ForegroundColor Red
Write-Host ""
Write-Host "Users are set with force-change-password-next-sign-in."
Write-Host "UPNs match the notebook's customers table for identity correlation."
